version: '3.8'

services:
  crate:
    image: crate:5.3.0
    ports:
      - 4100:5432
      - 4200:4200
    command: >
      crate -Cgateway.expected_nodes=1
            -Cgateway.recover_after_nodes=1
            -Cgateway.recover_after_time=5m
            -Cdiscovery.type=single-node

volumes:
  cratedb-data:
