version: '3.8'

services:
  redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
    networks:
      - mlcraft_default

  actions:
    build:
      context: ./services/actions/
    networks:
      - mlcraft_default

  cubejs:
    build:
      context: ./services/cubejs
    networks:
      - mlcraft_default

  hasura:
    build:
      context: ./services/hasura
    volumes:
      - ./services/hasura/migrations:/hasura-migrations
      - ./services/hasura/metadata:/hasura-metadata
      - ./services/hasura/seeds:/seeds
    environment:
      ENABLE_TELEMETRY: "false"
    networks:
      - mlcraft_default

  hasura_plus:
    build:
      context: ./scripts/containers/hasura-backend-plus
    volumes:
      - ./scripts/containers/hasura-backend-plus/storage-rules/rules.yaml:/app/custom/storage-rules/rules.yaml
    networks:
      - mlcraft_default

  cubestore:
    image: cubejs/cubestore:${CUBESTORE_VERSION:-v0.32.4}
    environment:
      - CUBESTORE_REMOTE_DIR=/cube/data
    volumes:
      - .cubestore:/cube/data
    networks:
      - mlcraft_default

networks:
  mlcraft_default:
    external: true
