version: '3.8'

services:
  redis:
    image: redis:5.0.8

  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: mlcraft_stack
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_DB: mlcraft_stack

  mlcraft_stack:
    restart: always
    build:
      context: ./scripts/containers/mlcraft-stack
    ports:
       - 80:80 # nginx app
       - 5000:5000 # frontend app
       - 8080:8080 # hasura
       - 3030:3030 # hasura-backend-plus
       - 3000:3000 # actions
       - 4000:4000 # cubejs
    volumes:
      - ./scripts/containers/mlcraft-stack/ecosystem.config.js:/app/ecosystem.config.js
      - ./scripts/containers/mlcraft-stack/nginx.conf:/app/nginx.conf
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://mlcraft_stack:pg_pass@postgres/mlcraft_stack
      HASURA_GRAPHQL_ADMIN_SECRET: mlcraft
    depends_on:
      - redis
      - postgres
