version: '3.8'

services:
  redis:
    image: redis:5.0.8
    networks:
      - mlcraft_default

  postgraphile:
    build:
      context: ./services/postgraphile/
    networks:
      - mlcraft_default

  actions:
    build:
      context: ./services/actions/
    networks:
      - mlcraft_default

  cubejs:
    build:
      context: ./services/cubejs
    networks:
      - mlcraft_default

  hasura:
    build:
      context: ./services/hasura
    volumes:
       - ./services/hasura/migrations:/hasura-migrations
       - ./services/hasura/metadata:/hasura-metadata
       - ./services/hasura/seeds:/seeds
    environment:
      ENABLE_TELEMETRY: "false"
    networks:
      - mlcraft_default

  hasura_plus:
    build:
      context: ./scripts/containers/hasura_backend_plus
    volumes:
       - ./scripts/containers/hasura_backend_plus/storage-rules/rules.yaml:/app/custom/storage-rules/rules.yaml
    networks:
      - mlcraft_default

networks:
  mlcraft_default:
    external: true
