version: '3.8'

services:
  postgres:
    image: postgres:12.2
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
       - 5435:5432
    volumes:
      - pgstorage-data:/var/lib/postgresql/data
      - ./etc/postgres.conf:/var/lib/postgresql/data/postgresql.conf
    env_file:
      - .stage.env
    networks:
      - mlcraft_default

  nginx:
    image: mesudip/nginx-proxy:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-ssl:/etc/ssl
    networks:
      - mlcraft_default
    environment:
      CLIENT_MAX_BODY_SIZE: 5m

  postgraphile:
    image: ${REGISTRY_HOST}/mlcraft/postgraphile:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    command: yarn start
    env_file:
      - .stage.env

  cubejs:
    image: ${REGISTRY_HOST}/mlcraft/cubejs-server:latest
    env_file:
      - .stage.env

  client:
    image: ${REGISTRY_HOST}/mlcraft/app-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    build:
      context: ./services/client/
    environment:
      HASURA_URL: ${PROTOCOL:-http}://api.${DOMAIN}/graphql
      GRAPHQL_WS_URL: ${WS_PROTOCOL:-ws}://api.${DOMAIN}/graphql
      VIRTUAL_HOST: ${PROTOCOL:-http}://app.${DOMAIN} -> :80
    networks:
      - mlcraft_default

  hasura:
    image: ${REGISTRY_HOST}/mlcraft/hasura:latest
    env_file:
      - .stage.env
    environment:
      VIRTUAL_HOST1: ${PROTOCOL:-http}://api.${DOMAIN} -> :8080
      VIRTUAL_HOST2: ${WS_PROTOCOL:-ws}://api.${DOMAIN} -> :8080

  hasura_plus:
    image: ${REGISTRY_HOST}/mlcraft/hasura-plus:latest
    env_file:
      - .stage.env
    environment:
      VIRTUAL_HOST: ${PROTOCOL:-http}://api-plus.${DOMAIN} -> :3000; client_max_body_size 5m;

volumes:
  pgstorage-data:
  nginx-dhparam:
  nginx-ssl:
