version: '3.8'

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: mlcraft_stack
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_DB: mlcraft_stack

  mlcraft_stack:
    restart: always
    build:
      context: ./scripts/containers/mlcraft-stack
    ports:
       - 80:80 # nginx app
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://mlcraft_stack:pg_pass@postgres/mlcraft_stack
      HASURA_GRAPHQL_ADMIN_SECRET: mlcraft
    depends_on:
      - postgres
