version: '3.8'

services:
  postgres:
    image: postgres:12.2
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
       - 5435:5432
    volumes:
      - pgstorage-data:/var/lib/postgresql/data
      - ./etc/postgres.conf:/var/lib/postgresql/data/postgresql.conf
    env_file:
      - .env
      - .stage.env
    networks:
      - mlcraft_default

  nginx:
    image: mesudip/nginx-proxy:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nginx-dhparam:/etc/nginx/dhparam
      - nginx-ssl:/etc/ssl
    networks:
      - mlcraft_default
    environment:
      CLIENT_MAX_BODY_SIZE: 5m

  cubejs:
    env_file:
      - .env
      - .stage.env

  client:
    image: ${REGISTRY_HOST}/mlcraft/app-client:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    build:
      context: ./services/client/
      args:
        NODE_ENV: test
    environment:
      VIRTUAL_HOST: ${PROTOCOL:-http}://app.${DOMAIN} -> :80
      GRAPHQL_SERVER_URL: ${PROTOCOL:-http}://api.${DOMAIN}/v1/graphql
      GRAPHQL_WS_URL: ${WS_PROTOCOL:-ws}://api.${DOMAIN}/v1/graphql
      GRAPHQL_PLUS_SERVER_URL: ${WS_PROTOCOL:-http}://api-plus.${DOMAIN}
    networks:
      - mlcraft_default

  hasura:
    env_file:
      - .env
      - .stage.env
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      VIRTUAL_HOST1: ${PROTOCOL:-http}://api.${DOMAIN} -> :8080
      VIRTUAL_HOST2: ${WS_PROTOCOL:-ws}://api.${DOMAIN} -> :8080
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 

  hasura_plus:
    env_file:
      - .env
      - .stage.env
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      VIRTUAL_HOST: ${PROTOCOL:-http}://api-plus.${DOMAIN} -> :3000; client_max_body_size 5m;
      SERVER_URL: ${PROTOCOL:-http}://api-plus.${DOMAIN}
      REDIRECT_URL_SUCCESS: ${PROTOCOL:-http}://app.${DOMAIN}/callback
      REDIRECT_URL_ERROR: ${PROTOCOL:-http}://app.${DOMAIN}/callback
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_SENDER: ${SMTP_SENDER}

  actions:
    env_file:
      - .env
      - .stage.env
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

volumes:
  pgstorage-data:
  nginx-dhparam:
  nginx-ssl:
