version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=password
    networks:
      - mlcraft_default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=user
      - ELASTICSEARCH_PASSWORD=password
    networks:
      - mlcraft_default
    depends_on:
      - elasticsearch

networks:
  mlcraft_default:
    name: mlcraft_default
