version: "3.9"

services:
  questdb:
    image: questdb/questdb:7.1.1
    ports:
      - 9005:9000
      - 8812:8812
      - 9009:9009
    environment:
      - QDB_PG_READONLY_USER_ENABLED=true
      - QDB_PG_READONLY_PASSWORD=quest
      - QDB_PG_READONLY_USER=quest
