version: '3.8'

services:
  postgres_test:
    container_name: postgres_test
    image: postgres:latest
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - druid_host=zookeeper
    env_file:
      - .test_env

  coordinator:
    image: apache/druid:25.0.0
    container_name: coordinator
    hostname: coordinator
    volumes:
      - druid_shared:/opt/shared
      - coordinator_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres_test
    ports:
      - "8084:8081"
    command:
      - coordinator
    environment:
      - druid_host=coordinator
    env_file:
      - .test_env

  broker:
    image: apache/druid:25.0.0
    container_name: broker
    hostname: broker
    volumes:
      - broker_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres_test
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    environment:
      - druid_host=broker
    env_file:
      - .test_env

  historical:
    image: apache/druid:25.0.0
    container_name: historical
    hostname: historical
    volumes:
      - druid_shared:/opt/shared
      - historical_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres_test
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    environment:
      - druid_host=historical
    env_file:
      - .test_env

  middlemanager:
    image: apache/druid:25.0.0
    container_name: middlemanager
    hostname: middlemanager
    volumes:
      - druid_shared:/opt/shared
      - middle_var:/opt/druid/var
    depends_on: 
      - zookeeper
      - postgres_test
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    environment:
      - druid_host=middlemanager
    env_file:
      - .test_env

  router:
    image: apache/druid:25.0.0
    container_name: router
    hostname: router
    volumes:
      - router_var:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres_test
      - coordinator
    ports:
      - "8889:8888"
    command:
      - router
    environment:
      - druid_host=router
    env_file:
      - .test_env

volumes:
  metadata_data: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_shared: {}
  grafana_data: {}
  kafka_data: {}
  zookeeper_data_kafka: {}